### ISSUE TITLE
Params validations

### ISSUE THREAD

**Issue by jodosha** [hanami/hanami-controller#22]
Right now, the `params` passed to `#call` are an instance of `Lotus::Action::Params` which is a nice wrapper around a Ruby Hash.

I would love to pass subclasses of `Params` which are aware of the specific use case and they should be able to do:
- [x] White label filtering: only the declared params will be available in the final object passed to `#call`.
- [ ] Coercions (optional feature): coerce a single param to the given Ruby class.
- [ ] Validations: if the given params aren't valid, halt with an HTTP status.

This approach has the following advantages:
- Avoid the need for low level entities to have mass assignment protection features.
- Save CPU cycles in case of validation failures: there is no need to hit lower layers if the data isn't valid.

We probably need to add this interface:

``` ruby
class Lotus::Action::Params
  def self.param(name, type, options = {})
    # ...
  end

  def initialize(params)
    @params = params
  end

  def validate!
    halt 412 unless valid?
  end

  def valid?
    # ...
  end
end
```

And implement one of those solutions:
### A

``` ruby
class Signup
  include Lotus::Action
  params SignupParams

  def call(params)
    puts params.class # => SignupParams
  end
end

class SignupParams < Lotus::Action::Params
  param :first_name, String, presence: true
  param :last_name,  String, presence: true
  param :email,      String, presence: true, format: /(.*)/
end
```

Where:

``` ruby
def self.params(params_class)
  before do |params|
    params_class.new(params).validate!
  end
end
```
### B

``` ruby
class Signup
  include Lotus::Action

  params do
    param :first_name, String, presence: true
    param :last_name,  String, presence: true
    param :email,      String, presence: true, format: /(.*)/
  end

  def call(params)
    puts params.class # => Signup::Params
  end
end
```

Where `.params` would generate an inner class of the action `Signup::Params`, which inherits from `Lotus::Action::Params`.

**Comment by sarahhenkens** [comment]
@jodosha The article is great on explaining what might go wrong. But what about a solution? Imagine a user model with a `username` and `email` field, both of these need to be unique. 

I do a POST and submit duplicate content for both fields. Relying on constraint exceptions will only trigger the first found constraint violation. Resulting in only it invalidating the first field. The user has to submit it again with the modified username to get the second validation constraint. 

Why not both? Add a uniqueness check in the validations block and also handle constraint violations properly in case the race condition DOES happen.

**Comment by beauby** [comment]
@sarahhenkens I believe you meant to comment on #232.

**Comment by jodosha** [comment]
@sarahhenkens Thanks for your input. 😄 Given the schema of a validation is totally decoupled from any entity/repository/database. How could be the syntax to indicate the uniqueness of a given field?

```ruby
params do
  required(:user).schema do
    required(:email).filled(:str?)
  end
end
```

In the case above `:user` maps the expected params, not an entity.

**Comment by sarahhenkens** [comment]
The way I've implemented it in my project at the moment is:
```
  class Validator
    include Hanami::Validations

    predicate :unique?, message: "must be unique" do |field, current|
      User.where(field => current).count == 0
    end

    predicate :email?, message: "must be an email" do |current|
      current =~ /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
    end

    validations do
      required(:email).filled(:str?, :email?) { unique?(:email) }
      required(:username).filled(:str?) { unique?(:username) }
      required(:password).filled(:str?)
    end
  end
```

I've added a `unique?` predicate that is currently coupled to my model layer.

**Comment by beauby** [comment]
I've been doing roughly the same as @sarahhenkens.

**Comment by beauby** [comment]
@jodosha I'd be in favor of an example in the docs, as providing a standard predicate would force to many assumptions. My main concern was that in #232, the discussion seemed to imply that the maintainers would label uniqueness validations as "bad practice", whereas it is kind of unavoidable in certain cases.

**Comment by jodosha** [comment]
@beauby the only problem that I have by adding to the guides is that everything documented there will eventually become the "Hanami way". Honestly I won't push for that uniqueness validation.

WDYT?

**Comment by beauby** [comment]
@jodosha I may be missing something but I don't see any other solution than uniqueness validations for informing the user about which field broke a uniqueness constraint (except when there's only one). Hence, I'm advocating for uniqueness validations to become the "Hanami way". FWIW, I remember discussing this with @solnic who held the same views.

**Comment by AlfonsoUceda** [comment]
@beauby @jodosha we can document the uniqueness validation but this validation will have to be implemented by the user because it will be coupled with the repository. This is the only validation I see, we can suggest to be coupled with a repository. what do you think?

**Comment by jodosha** [comment]
@beauby I agree that using exceptions for control flow isn't ideal. But what is worst is to rely on a race condition to validate data.

I've seen too many Rails apps with an _uniqueness validation_ without the corresponding database constraint. I just want to avoid this situations in Hanami projects.

---

How to move on from this? I have a few suggestions:

  1. I'm working on a spike to eventually include in Hanami 1.1, where the `Hanami::Model::UniqueConstraintViolationError` exposes the column/constraint that it has been violated via getters
  2. With https://github.com/hanami/controller/pull/232, you can add an error message, by inspecting the error. We're still in Hanami 1.1.
  3. To have in Hanami 2.0, the errors to be returned instead of raised exceptions. A developer can match the returning value of a repository action and act accordingly. This is still an experiment.
