### ISSUE TITLE
Inheritance bug

### ISSUE THREAD

**Issue by eriklott** [hanami/hanami-controller#39]
I'm using lotus-controller 0.2.0

A standalone controller/action is returning a valid rack response:

``` ruby
require 'lotus/controller'
module MyApp
  class MyAction
    include Lotus::Action
    def call(params)
      self.body = 'hello'
    end
  end
end

# MyApp::MyAction.call({}) => [200, {"Content-Type"=>"application/octet-stream"}, ["hello"]]
```

However, if I inherit from a base class, an invalid response is being generated

``` ruby
require 'lotus/controller'
module MyApp
  class BaseAction
    include Lotus::Action
  end
end

module MyApp
  class MyAction < BaseAction
    def call(params)
      self.body = 'hello'
    end
  end
end
# MyApp::MyAction.call({}) => "hello"
```

Bug?

My original intention is to add a few simple authentication before filters to the base class so that they can be inherited by all subclasses.. but it doesn't look like inheritance is working.

**Comment by danelowe** [comment]
@jodosha Is this behaviour likely to change at all?

Composition works well for including features such as authentication, but there are also many situations where I suggest one might want to inherit controllers. e.g:

* Create and Update actions that each operate on the same object and need to set up the same exposures, repositories, state, session objects etc. 
* Actions that are mostly similar but vary in some way, e.g. actions that update products, but are each intended to save different data and render different forms.
